<h2>Tratamentos necessários identificados:
    - Remover colunas sem nome e dados;
    - Trocar o tipo de dado da coluna DATA;
    - Remover colunas nulas (PR_ID == 107).

Importando pandas e lendo o arquivo csv

In [19]:
import pandas as pd

In [20]:
df = pd.read_csv("../data/raw.csv", delimiter=";")

Removendo colunas vazias

In [21]:
df = df.drop(columns=["Unnamed: 10","Unnamed: 11","Unnamed: 12","Unnamed: 13"])

In [22]:
df.head()

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO

Trocar o tipo de dado da coluna DATA

In [23]:
df["DATA"] = pd.to_datetime(df["DATA"], format="%d/%m/%Y")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 10 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   DATA       830000 non-null  datetime64[us]
 1   CO_ID      830000 non-null  int64
 2   CL_ID      830000 non-null  int64
 3   CL_GENERO  830000 non-null  str
 4   CL_EC      830000 non-null  int64
 5   CL_FHL     830000 non-null  int64
 6   CL_SEG     830000 non-null  str
 7   PR_ID      830000 non-null  int64
 8   PR_CAT     830000 non-null  str
 9   PR_NOME    830000 non-null  str
dtypes: datetime64[us](1), int64(5), str(4)
memory usage: 63.3 MB

Trocando o tipo de dado das colunas de id para string - Optei em fazer para evitar calculos com colunas de id, que devem ser únicas.

In [24]:
x = ["CO_ID","CL_ID","PR_ID"]

for i in x:
    df[i] = df[i].astype("str")

Removendo colunas nulas

In [ ]:
df[df["PR_ID"]=="107"]

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
82,2019-02-01,1078,290,F,1,0,B,107,#N/D,#N/D
223,2019-02-01,1103,957,M,2,3,B,107,#N/D,#N/D
640,2019-02-01,1482,453,F,1,0,B,107,#N/D,#N/D
857,2019-02-01,1683,438,F,1,0,B,107,#N/D,#N/D
917,2019-02-01,1793,608,F,3,0,C,107,#N/D,#N/D
...,...,...,...,...,...,...,...,...,...,...
829528,2022-08-19,919578,567,F,1,0,C,107,#N/D,#N/D
829602,2022-08-19,919626,758,F,3,0,B,107,#N/D,#N/D
829787,2022-08-19,919716,801,M,1,4,B,107,#N/D,#N/D
829829,2022-08-19,919716,801,M,1,4,B,107,#N/D,#N/D
829882,2022-08-19,919770,888,F,4,2,B,107,#N/D,#N/D

In [38]:
df = df.drop(df.loc[df["PR_ID"]=="107"].index)
df.shape

(826350, 10)

Exportando o dataset processado

In [40]:
# Organizando o índice depois de todo tratamento
df = df.reset_index(drop=True)

In [42]:
#Exportação
df.to_csv("../data/processed.csv", index=False)